### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by pablocrivella** [mhahn/vagrant-librarian-puppet#12]
I installed the plugin on my windows machine and i got this error message when i try to run any vagrant command:

```
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

Permission denied - puppet
```

Do i have to install puppet and/or librarian-puppet gem on my windows machine to make this work?

**Comment by jhoblitt** [comment]
Is anyone able to reproduce this on a clean vagrant box?  It sounds like an environment setup issue.

**Comment by mlt** [comment]
I think this is old and can be closed? I recently wiped out vagrant (and removed C:\HashiCorp\ along with ~/.vagrant.d/gems/ and ~/.vagrant.d/plugins.json) and reinstalled it along with this plug-in on Windows 8.1 Pro 64 bit. Everything works well.
