### ISSUE TITLE
Configuring puppetfile_dir doesn't work

### ISSUE THREAD

**Issue by habitullence** [mhahn/vagrant-librarian-puppet#19]
For me ```config.librarian_puppet.puppetfile_dir = 'puppet'``` stops the plugin working. Without it modules get installed ok but with it nothing seems to happen and then puppet complains about not being able to find classes etc.

**Comment by tuxinaut** [comment]
Same here

**Comment by jhoblitt** [comment]
The Vagrant puppet provisioner needs to have it's module path set to match where librarian-puppet is installing the modules:

From the README:

```
You may specify the subdirectory within which to run `librarian-puppet`
using the `librarian_puppet.puppetfile_dir` config key.  Please keep in mind
that you will need to explicitly set the `modules` path in the
`:puppet` provisioner and this path must exist before running vagrant commands.
```
