### ISSUE TITLE
bump librarian-puppet version in dependencies

### ISSUE THREAD

**Issue by ivan-kolmychek** [mhahn/vagrant-librarian-puppet#23]
required `librarian-puppet` version fails to install any module with `Puppetfile` generated by `1.3.2` version, because of new puppet forge url:

> forge "https://forgeapi.puppetlabs.com"

so, maybe it's a good idea to bump `librarian-puppet` version in requirements =)

**Comment by mhahn** [comment]
going to bump to 1.4.1 since 2.x requires ruby 1.9
