### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by ErikEvenson** [mhahn/vagrant-librarian-puppet#30]
Would be nice to have a changelog to know what has changed.  Thanks for the helpful tool!

**Comment by tuxinaut** [comment]
:+1:

**Comment by jhoblitt** [comment]
Shazam! https://github.com/mhahn/vagrant-librarian-puppet/blob/master/CHANGELOG.md

**Comment by ErikEvenson** [comment]
Boom!  Thanks!
