### ISSUE TITLE
librarian-puppet not working with error name (nil) must be sensible (ArgumentError)

### ISSUE THREAD

**Issue by fhenri** [mhahn/vagrant-librarian-puppet#42]
I have just installed the plugin to simplify librarian process but face an issue

on host :
 - vagrant 1.7.4 
 - vagrant-librarian-puppet (0.9.0) 

on guest :
 - puppet_version=3.8.2
 - ruby_version=1.8.7

Vagrantfile is as following

    config.librarian_puppet.puppetfile_dir = "puppet"
    config.librarian_puppet.use_v1_api = '1'
    config.librarian_puppet.destructive = false
    config.vm.provision "puppet" do |p|
      p.module_path = "puppet/modules"
      p.manifests_path = "puppet/manifests"
      p.manifest_file = "site.pp"
      p.options = "--verbose --debug"
    end

with `puppet` and `puppet/modules` directory created

Puppetfile is simple

    forge "https://forge.puppetlabs.com"

    mod 'spantree-java8'
    mod 'locp-cassandra', "1.6.0"

when running provisioning (vagrant up or vagrant provision) I get the following error

    fhenri@machine:~/project/examples/vagrant/testbox.puppet$ vagrant provision
    ==> default: Installing Puppet modules in "puppet" with Librarian-Puppet...
    /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/dependency.rb:149:in `assert_name_valid!': name (nil) must be sensible (ArgumentError)
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-puppet-2.0.1/lib/librarian/puppet/extension.rb:14:in `initialize'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-puppet-2.0.1/lib/librarian/puppet/source/forge.rb:147:in `new'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-puppet-2.0.1/lib/librarian/puppet/source/forge.rb:147:in `block in fetch_dependencies'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-puppet-2.0.1/lib/librarian/puppet/source/forge.rb:145:in `each'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-puppet-2.0.1/lib/librarian/puppet/source/forge.rb:145:in `map'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-puppet-2.0.1/lib/librarian/puppet/source/forge.rb:145:in `fetch_dependencies'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/manifest.rb:125:in `fetch_dependencies!'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/manifest.rb:117:in `fetched_dependencies'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/manifest.rb:81:in `dependencies'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:117:in `block in check_manifest_for_cycles'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:117:in `each'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:117:in `map'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:117:in `check_manifest_for_cycles'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:64:in `block in recursive_resolve'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:154:in `block (3 levels) in resolving_dependency_map_find_manifests'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:187:in `block in scope_checking_manifest'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:186:in `scope_checking_manifest'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:153:in `block (2 levels) in resolving_dependency_map_find_manifests'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:211:in `block in map_find'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:210:in `each'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:210:in `map_find'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:152:in `block in resolving_dependency_map_find_manifests'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:165:in `block (2 levels) in scope_resolving_dependency'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:179:in `block in scope_checking_manifests'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:178:in `scope_checking_manifests'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:164:in `block in scope_resolving_dependency'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:163:in `scope_resolving_dependency'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:151:in `resolving_dependency_map_find_manifests'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:62:in `recursive_resolve'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:50:in `resolve'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver.rb:23:in `resolve'
      from /Users/fhenri/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/action/resolve.rb:26:in `run'
      from /Users/fhenri/.vagrant.d/gems/gems/vagrant-librarian-puppet-0.9.0/lib/vagrant-librarian-puppet/action/librarian_puppet.rb:63:in `provision'

cannot find a reference to this error, only thing that google can retrieve is https://jira.duraspace.org/browse/DS-2734 where they mention to increment the version of librarian-puppet to latest one.

could it be something that is considered for this project too ?

**Comment by fhenri** [comment]
To complement I also try with another box with updated ruby and still the same issue

    vagrant@precise64:~$ ruby --version
    ruby 1.9.3p374 (2013-01-15 revision 38858) [x86_64-linux]

**Comment by amerdidit** [comment]
The following pull request will fix this issue: https://github.com/mhahn/vagrant-librarian-puppet/pull/41
